input_text: |
  instruction: Identify the verb in the following sentence: The cat sleeps on the couch.
look_back: 256
num_tokens_to_generate: 20
top_k : 2
temperature : 1.0
eos_id : null
device : 'cpu'