[project]
name = "foundation-llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.4",
    "tiktoken>=0.9.0",
    "torch>=2.6.0",
    "wandb>=0.19.11",
]
